name: Build & Deploy Utility Apis

on:
  push:
    branches:
      -main


jobs:
  build-deploy:
    name: Build & Deploy Utility Apis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api:
          - Quotes-Generation 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

    
      - name: Build Utility Jars
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build & Push ${{ matrix.api }} image
        uses: docker/build-push-action@v6
        with: 
          context: ./${{ matrix-api }}
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ ${{ matrix.api }}:latest
